name: Mirror Container Images

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: 'Source image name (e.g. nginx:1234 or abc/nginx:1234)'
        required: true

jobs:
  mirror-image:
    runs-on: ubuntu-latest
    env:
      TARGET_REGISTRY: ${{ secrets.NEW_REGISTRY_BASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Login to source registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.SOURCE_REGISTRY_BASE }}
      #     username: ${{ secrets.SOURCE_REG_USER }}
      #     password: ${{ secrets.SOURCE_REG_PASSWORD }}

      - name: Login to target registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEW_REGISTRY_BASE }}
          username: ${{ secrets.TARGET_REG_USER }}
          password: ${{ secrets.TARGET_REG_PASSWORD }}

      - name: Transform and push image
        run: |
          chmod +x scripts/transform-image.sh
          ./scripts/transform-image.sh "${{ inputs.source_image }}"

      - name: Upload mapping logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-mappings
          path: logs/image-mappings.json
          retention-days: 7
